import type { NextPage } from 'next';

import Head from 'next/head';

import { trpc } from '../utils/trpc';

const Home: NextPage = () => {
    const hello = trpc.useQuery(['example.hello', { text: 'from tRPC' }]);
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="mx-auto flex max-w-3xl flex-col items-center justify-start space-y-4 sm:flex-row sm:items-end sm:justify-around sm:space-y-0">
                <div className="w-full max-w-lg divide-y divide-layer-3">
                    <label className="block py-4">
                        <div className="flex h-full items-center space-x-4">
                            <input
                                type="checkbox"
                                name="inputName"
                                id="inputName:1"
                                className="h-5 w-5 rounded border-2 border-text bg-transparent text-primary focus:ring-primary focus:ring-offset-0 checked:focus:ring-text disabled:opacity-30"
                            />
                            <h4 className="text-base font-semibold text-white">
                                Check Item
                            </h4>
                        </div>
                        <p className="mt-2 ml-9 text-sm font-medium text-text">
                            Lorem ipsum dolor sit amet, consectetur adipiscing
                            elit. Elementum hac porttitor.
                        </p>
                    </label>
                    <label className="block py-4">
                        <div className="flex items-center space-x-4">
                            <input
                                type="checkbox"
                                name="inputName"
                                id="inputName:2"
                                className="h-5 w-5 rounded border-2 border-text bg-transparent text-primary focus:ring-primary focus:ring-offset-0 checked:focus:ring-text disabled:opacity-30"
                            />
                            <h4 className="text-base font-semibold text-white">
                                Check Item
                            </h4>
                        </div>
                        <p className="mt-2 ml-9 text-sm font-medium text-text">
                            Lorem ipsum dolor sit amet, consectetur adipiscing
                            elit. Elementum hac porttitor.
                        </p>
                    </label>
                    <label className="block py-4">
                        <div className="flex items-center space-x-4">
                            <input
                                type="checkbox"
                                name="inputName"
                                id="inputName:3"
                                className="h-5 w-5 rounded border-2 border-text bg-transparent text-primary focus:ring-primary focus:ring-offset-0 checked:focus:ring-text disabled:opacity-30"
                            />
                            <h4 className="text-base font-semibold text-white">
                                Check Item
                            </h4>
                        </div>
                        <p className="mt-2 ml-9 text-sm font-medium text-text">
                            Lorem ipsum dolor sit amet, consectetur adipiscing
                            elit. Elementum hac porttitor.
                        </p>
                    </label>
                </div>
                <div className="flex justify-center">
                    <div className="timepicker form-floating relative mb-3 xl:w-96">
                        <input
                            type="text"
                            className="form-control m-0 block w-full rounded border border-solid border-gray-300 bg-white bg-clip-padding px-3 py-1.5 text-base font-normal text-gray-700 transition ease-in-out focus:border-blue-600 focus:bg-white focus:text-gray-700 focus:outline-none"
                            placeholder="Select a date"
                        />
                        <label
                            htmlFor="floatingInput"
                            className="text-gray-700"
                        >
                            Select a time
                        </label>
                        <button
                            tabIndex={0}
                            type="button"
                            className="timepicker-toggle-button"
                            data-mdb-toggle="timepicker"
                        >
                            <i className="fas fa-clock timepicker-icon"></i>
                        </button>
                    </div>
                </div>
            </div>
        </>
    );
};

export default Home;
